
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[390] =
    {   0,
       46,   46,   51,   49,   50,   48,   49,   50,   47,   48,
       50,   49,   50,    1,   49,   50,   49,   50,   35,   49,
       50,   36,   49,   50,   49,   50,   49,   50,   39,   49,
       50,   49,   50,   49,   50,   33,   49,   50,   40,   49,
       50,   37,   49,   50,   38,   49,   50,   41,   49,   50,
       41,   49,   50,   41,   49,   50,   41,   49,   50,   41,
       49,   50,   41,   49,   50,   41,   49,   50,   41,   49,
       50,   41,   49,   50,   41,   49,   50,   41,   49,   50,
       41,   49,   50,   41,   49,   50,   41,   49,   50,   41,
       49,   50,   37,   49,   50,   49,   50,   44,   50,   50,

       50,   46,   50,   50,    2,   50,   41,   49,   50,   41,
       49,   50,   41,   49,   50,   41,   49,   50,   41,   49,
       50,   41,   49,   50,   41,   49,   50,   41,   49,   50,
       41,   49,   50,   41,   49,   50,   41,   49,   50,   48,
       45,   34,   42,   23,   23,   21,   33,   21,   22,   33,
       22,   24,   24,   33,   30,   41,   41,   41,   41,   41,
    16416,   41,16416,   41,   41,16415,   41,   41,   41,   41,
    16415,   41,   41,16415,   41,   41,16415,   41,16415,   41,
       41,   41,16415,   29,   41,   41,   41,    5,   41,   41,
       26,   26,   44,   43,   46,    2,   41,   41,   41,   41,

       13,   41,   41,   41,   41,   41,   41,   41,   23,   23,
       23,   21,   21,   21,   21,   22,   22,   22,   22,   24,
       24,   24,   28,   41,   41,   41,   41, 8223,   41,   41,
       41,   41,   41,   41,   41,   41,   27,   41,   12,   41,
       41,   41,   41,   26,   26,   26,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   23,   21,   22,   24,
       41,   41, 8224,   41,   41,   41,   41,   41,   41,   41,
       41,   25,   41,   25,   41,   41,   41,   41,   26,   41,
        6,   41,   41,   41,   41,   41,   41,   10,   41,   41,
       41,   41,    4,   41,   41,   41,   41,   41,    4,   41,

       41,   41,   25,   25,   25,   25,   41,   25,   41,    4,
       41,   41,   16,   41,   41,   41,   14,   41,   41,   17,
       41,   41,   41,   41,   41,    4,   41,   41,   41,   41,
        4,   41,    3,   41,   19,   25,   25,   25,   41,   41,
       41,   41,   41,   41,   41,    9,   41,   41,   41,   19,
       19,    4,   41,   41,   41,   41,   41,   10,   41,   41,
       20,   41,    4,   41,   41,    8,   41,   41,   41,   41,
       20,   20,   41,    7,   41,   15,   41,   41,   41,    4,
       41,   41,   41,   18,   41,   41,   41,   11,   41
    } ;

static const flex_int16_t yy_accept[337] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    6,    9,   12,   14,   17,   19,
       22,   25,   27,   29,   32,   34,   36,   39,   42,   45,
       48,   51,   54,   57,   60,   63,   66,   69,   72,   75,
       78,   81,   84,   87,   90,   93,   96,   98,  100,  101,
      102,  104,  105,  107,  110,  113,  116,  119,  122,  125,
      128,  131,  134,  137,  140,  141,  142,  142,  143,  143,
      143,  143,  143,  144,  144,  145,  146,  146,  146,  146,
      146,  148,  149,  149,  149,  149,  149,  151,  152,  152,

      152,  152,  152,  153,  154,  155,  156,  157,  158,  159,
      160,  162,  164,  165,  167,  168,  169,  170,  172,  173,
      175,  176,  178,  180,  181,  182,  184,  186,  187,  188,
      190,  191,  191,  191,  191,  191,  192,  193,  194,  194,
      195,  196,  196,  197,  198,  199,  200,  201,  203,  204,
      205,  206,  207,  208,  209,  209,  210,  210,  210,  211,
      212,  213,  213,  214,  214,  214,  215,  216,  217,  217,
      218,  218,  218,  219,  220,  220,  221,  221,  221,  222,
      223,  225,  226,  227,  227,  228,  229,  230,  231,  232,
      233,  234,  235,  236,  237,  239,  241,  242,  243,  244,

      244,  245,  245,  245,  246,  247,  248,  249,  250,  251,
      252,  253,  254,  255,  256,  257,  258,  259,  260,  261,
      262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
      272,  272,  272,  272,  272,  274,  276,  277,  278,  279,
      280,  281,  283,  284,  285,  286,  287,  288,  290,  291,
      292,  293,  295,  296,  297,  298,  299,  301,  302,  303,
      303,  304,  305,  305,  306,  306,  306,  308,  310,  312,
      313,  315,  316,  317,  319,  320,  322,  323,  324,  325,
      326,  328,  329,  330,  331,  333,  335,  335,  336,  337,
      338,  339,  340,  341,  342,  343,  344,  345,  346,  348,

      348,  349,  350,  351,  352,  354,  355,  356,  357,  358,
      360,  361,  361,  362,  363,  365,  366,  368,  369,  370,
      371,  372,  373,  374,  376,  378,  379,  380,  382,  383,
      384,  386,  387,  388,  390,  390
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
        1,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   28,   28,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   28,   28,   28,   40,   28,
       41,    1,   42,   43,    1,    1,   44,   45,   46,   47,

       48,   49,   50,   28,   51,   28,   28,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   28,   28,   28,
       62,   28,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    3,    1,    1,    4,    5,    1,    1,    6,
        5,    1,    5,    1,    1,    7,    1,    1,    1,    1,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[375] =
    {   0,
        0,    0,   60,   61, 1039, 1038, 1034, 1033,    0,    0,
       49,   53,   42,   43,   56,   59,   62,   63,   70,   97,
       51,   64, 1038, 1043,  122,  125, 1032, 1030, 1028, 1043,
     1043,  129,  145, 1043,  153,  161, 1018, 1043, 1020, 1043,
      116, 1016,  141,  149,  155,  159,  170,  162,  172,  168,
      182,  166,  188,  212,  213, 1043,  229, 1021, 1043, 1020,
        0, 1023, 1043,  228,   83,  222,  238,  151,  239,  254,
      263,  232,  270,  273,  177, 1043, 1022, 1043, 1020,  320,
     1020, 1018, 1043, 1008,  211, 1007,  332, 1016, 1014, 1004,
      244, 1003,  340, 1012, 1010, 1000,  250,  999,  348, 1008,

     1006,  996,  291,  995,  994, 1043,  993,  992,  106,  313,
      294,  297,  268,  307,  342,  341,  319,  360,  344,  365,
      353,  370,  371,  316,  363,  373,  991,  362,  369,  990,
      368,  408,  999,  997,  987,  305,  983,  988,  987, 1043,
        0,  990, 1043,  375,  378,  377,  381,  385,  380,  390,
      412,  416,  251,  414,  989, 1043,  981,  971,  970,  969,
      419,  978, 1043,  955,  943,  939,  936,  426,  841, 1043,
      833,  818,  815,  809,  816, 1043,  811,  799,  795,  792,
      785,  427,  420,  435,  425,  756,  440,  441,  443,  439,
      445,  447,  446,  490,  741,  740,  448,  455,  449,  749,

     1043,  746,  736,  735,  734,  472,  486,  465,  468,  496,
      498,  497,  504,  505,  499,  731,  730,  728,  727,  507,
      501,  725,  502,  513,  508,  515,  523,  528,  536,  125,
      564,  734,  731,  720,  475,  719,  530,  553,  551,  717,
      527,  713,  552,  557,  565,  563,  570,  705,  573,  575,
      576,  650,  577,  578,  593,  579,  639,  591,  582,  651,
      586,  583,  556, 1043,  548,  524,  479,  463,  438,  602,
      395,  601,  607,  392,  608,  367,  613,  610,  617,  615,
      352,  300,  618,  626,  325,  321,  310,  295,  271,  264,
      255,  628,  631,  612,  641,  636,  643,  642,  234,  245,

      638,  663,  230,  221,  203,  653,  664,  669,  674,  197,
      684,  205,  190,  665,  175,  675,  138,  676,  671,  678,
      134,  133,  695,  122,  118,  694,  697,  102,  704,  698,
       98,  701,  690,   57, 1043,  759,  767,  775,  783,  791,
      798,  805,  812,  819,  821,  828,  836,  844,  852,  860,
      868,  870,  878,  886,  888,  896,  904,  906,  914,  922,
      924,  932,  940,  942,  949,  956,  964,  972,  974,  981,
      983,  985,  992,  994
    } ;

static const flex_int16_t yy_def[375] =
    {   0,
      335,    1,  336,  336,  337,  337,  338,  338,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  335,  335,  335,  335,  335,  339,  340,  335,
      335,  341,  342,  335,  343,  344,  335,  335,  335,  335,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  335,  346,  347,  335,  335,
      348,  349,  335,  345,   45,  345,  345,   45,  345,  345,
      345,  345,  345,  345,  335,  335,  339,  335,  340,  341,
      350,  351,  335,  335,  335,  352,  342,  353,  354,  335,
      335,  355,  343,  356,  357,  335,  335,  358,  344,  359,

      360,  335,  335,  361,  335,  335,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  346,  362,  363,  335,  335,  364,  347,  335,  335,
      348,  349,  335,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  350,  335,  351,  335,  352,  352,
      335,  353,  335,  354,  335,  355,  355,  335,  356,  335,
      357,  335,  358,  358,  359,  335,  360,  335,  361,  361,
      345,  345,  345,  335,  345,  335,  345,  345,  345,  345,
      345,  345,  345,  365,  345,  345,  345,  345,  345,  362,

      335,  363,  335,  364,  364,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  335,  335,  335,  335,  345,
      345,  335,  345,  345,  345,  345,  345,  345,  345,  345,
      366,  367,  368,  335,  345,  369,  345,  345,  345,  335,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  370,
      335,  371,  367,  335,  368,  335,  369,  369,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  370,  372,  371,  371,
      335,  345,  345,  345,  345,  345,  345,  345,  345,  373,

      345,  345,  372,  372,  345,  345,  345,  345,  345,  345,
      345,  373,  374,  345,  345,  345,  345,  345,  345,  345,
      374,  374,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,    0,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335
    } ;

static const flex_int16_t yy_nxt[1109] =
    {   0,
       24,   25,   26,   25,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   24,   36,   37,   34,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   42,   48,   49,
       50,   51,   52,   53,   42,   42,   54,   55,   42,   42,
       56,   40,   57,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   42,   42,   54,   55,
       42,   42,   56,   34,   40,   59,   59,   66,   66,   60,
       60,   64,  107,   65,   66,   64,   74,   65,   66,   67,
       68,   69,   67,   68,   69,   70,   70,   71,   71,   74,
       66,   66,   72,   73,   64,   74,   65,   66,   64,   74,

       65,   66,   67,   68,   69,   67,   68,   69,   70,   70,
       71,   71,   74,  107,  145,   72,   73,  107,   74,   72,
       73,  107,   74,   75,   75,   75,   75,   75,   75,  181,
       80,  107,  260,  107,   81,   82,  145,  107,   83,   84,
      107,   84,   72,   73,   85,   74,   87,  109,  321,  321,
       88,   89,  181,  107,   93,   90,  107,   90,   94,   95,
       91,  110,   99,   96,  107,   96,  100,  101,   97,  109,
      107,  102,  111,  102,  107,  112,  103,  107,   75,   75,
       75,  107,  148,  107,  110,  107,  113,  107,  117,  114,
      107,  115,  116,  121,  118,  111,  122,  107,  112,  119,

      124,  127,  125,  107,  148,  321,  312,  120,  113,  123,
      117,  114,  107,  115,  116,  121,  126,  118,  107,  122,
      128,  119,  124,  127,  158,  125,   85,  107,  107,  120,
      132,  123,  129,  131,  133,  134,  303,  107,  126,  135,
      130,  135,  128,  107,  136,  303,  312,  107,  110,  107,
      146,  117,  152,  107,  107,  129,  131,  165,  147,   91,
      144,  111,  130,  172,  112,   97,  107,  149,  117,  107,
      291,  110,  146,  117,  150,  152,  214,  111,  107,  289,
      112,  147,  144,  107,  111,  107,  289,  112,  107,  149,
      117,  151,  117,  111,  153,  184,  112,  150,  184,  214,

      111,  154,  117,  112,  178,  185,  103,  300,  186,  107,
      303,  287,  107,  151,  117,  107,  111,  153,  203,  112,
      136,   80,  107,  154,  117,   81,   82,  185,  107,  335,
       84,  107,   84,   87,  107,   85,  107,   88,   89,  194,
      107,   93,   90,  182,   90,   94,   95,  161,  183,   99,
       96,  190,   96,  100,  101,  168,  107,  107,  102,  107,
      102,  186,  194,  103,  187,  182,  186,  107,  107,  189,
      183,  186,  186,  190,  186,  107,  191,  107,  107,  188,
      107,  192,  107,  107,  107,  107,  107,  187,  107,  198,
      107,  189,  107,  107,  193,  107,  107,  196,  191,  199,

      107,  188,  195,  192,  197,  107,  206,  107,  208,  132,
      107,  210,  198,  133,  134,  207,  209,  193,  135,  196,
      135,  199,  185,  136,  195,  211,  197,  107,  206,  107,
      208,  107,  165,  210,  161,  107,  184,  207,  209,  172,
      107,  168,  107,  212,  185,  215,  182,  211,  220,  223,
      222,  183,  213,  107,  107,  107,  107,  221,  107,  227,
      107,  107,  107,  107,  107,  212,  228,  215,  182,  229,
      107,  220,  223,  183,  213,  224,  225,  226,  267,  221,
      107,  230,  227,  107,  238,  237,  239,  107,  266,  228,
      235,  231,  229,  243,  267,  232,  233,  224,  225,  226,

      234,  107,  234,  230,  244,  235,  238,  237,  239,  241,
      223,  107,  107,  107,  107,  243,  107,  107,  242,  107,
      107,  252,  107,  107,  245,  247,  244,  250,  107,  249,
      107,  241,  255,  223,  246,  251,  248,  253,  107,  291,
      242,  254,  107,  107,  252,  107,  245,  247,  258,  250,
      269,  107,  249,  256,  264,  255,  246,  251,  248,  253,
      257,  264,  272,  254,  259,  231,  107,  107,  107,  232,
      233,  258,  107,  269,  234,  256,  234,  270,  107,  261,
      107,  274,  257,  271,  272,  107,  259,  276,  107,  273,
      107,  107,  107,  107,  107,  278,  280,  107,  289,  266,

      270,  261,  275,  284,  274,  271,  107,  277,  107,  281,
      276,  273,  279,  282,  286,  283,  107,  107,  278,  280,
      285,  293,  107,  107,  275,  107,  284,  107,  107,  277,
      107,  281,  107,  107,  279,  282,  286,  292,  283,  294,
      295,  107,  285,  107,  293,  296,  107,  297,  307,  298,
      299,  107,  287,  107,  107,  301,  107,  107,  107,  292,
      305,  294,  295,  302,  311,  107,  306,  296,  107,  297,
      307,  298,  299,  309,  308,  310,  314,  301,  107,  107,
      107,  316,  305,  315,  107,  302,  107,  311,  306,  107,
      107,  107,  317,  107,  319,  309,  308,  310,  314,  107,

      323,  318,  326,  316,  320,  107,  315,  324,  327,  107,
      107,  325,  107,  107,  317,  328,  107,  319,  330,  107,
      107,  333,  323,  318,  326,  334,  332,  320,  107,  324,
      327,  329,  240,  325,  267,  261,  331,  264,  328,  264,
      222,  330,  219,  218,  333,  217,  216,  334,  332,  204,
      204,  240,  201,  329,  201,  107,  107,  186,  331,   58,
       58,   58,   58,   58,   58,   58,   58,   61,   61,   61,
       61,   61,   61,   61,   61,   62,   62,   62,   62,   62,
       62,   62,   62,   77,   77,   77,   77,   77,   77,   77,
       77,   79,   79,   79,   79,   79,   79,   79,   79,   86,

      107,   86,   86,   86,   86,   86,   92,  179,   92,   92,
      179,   92,   92,   98,  219,   98,   98,  176,   98,   98,
      104,  176,  104,  104,  173,  104,  104,  108,  108,  137,
      173,  137,  137,  218,  137,  137,  138,  138,  138,  170,
      138,  138,  138,  138,  141,  141,  170,  141,  141,  141,
      141,  141,  142,  142,  142,  142,  142,  142,  142,  142,
      155,  155,  155,  155,  155,  155,  155,  155,  157,  157,
      157,  157,  157,  157,  157,  157,  160,  160,  162,  162,
      162,  162,  162,  162,  162,  162,  164,  164,  164,  164,
      164,  164,  164,  164,  167,  167,  169,  169,  169,  169,

      169,  169,  169,  169,  171,  171,  171,  171,  171,  171,
      171,  171,  174,  174,  175,  175,  175,  175,  175,  175,
      175,  175,  177,  177,  177,  177,  177,  177,  177,  177,
      180,  180,  200,  200,  200,  200,  200,  200,  200,  200,
      202,  202,  202,  202,  202,  202,  202,  202,  205,  205,
      236,  166,  236,  236,  166,  236,  236,  262,  217,  262,
      262,  163,  262,  262,  263,  263,  263,  263,  263,  263,
      263,  263,  265,  265,  265,  265,  265,  265,  265,  265,
      268,  268,  288,  163,  159,  159,  216,  156,  288,  290,
      290,  304,  304,  313,  156,  143,  140,  139,  204,  313,

      322,  322,  136,  201,  201,  107,  107,  107,  107,  105,
      179,  103,  176,  176,  173,  168,  170,  170,  166,  161,
      163,  163,  159,   85,  156,  156,   78,   78,  143,  140,
      139,  107,  106,  105,   78,   78,   76,  335,   63,   63,
       59,   59,   23,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335
    } ;

static const flex_int16_t yy_chk[1109] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,   13,   14,    3,
        4,   11,  334,   11,   11,   12,   21,   12,   12,   15,
       15,   15,   16,   16,   16,   17,   18,   17,   18,   22,
       13,   14,   19,   19,   11,   19,   11,   11,   12,   21,

       12,   12,   15,   15,   15,   16,   16,   16,   17,   18,
       17,   18,   22,  331,   65,   19,   19,  328,   19,   20,
       20,  109,   20,   25,   25,   25,   26,   26,   26,  109,
       32,   41,  230,  325,   32,   32,   65,  324,   32,   32,
      230,   32,   20,   20,   32,   20,   33,   41,  322,  321,
       33,   33,  109,  317,   35,   33,   43,   33,   35,   35,
       33,   43,   36,   35,   44,   35,   36,   36,   35,   41,
       45,   36,   44,   36,   46,   44,   36,   48,   75,   75,
       75,   52,   68,   50,   43,   47,   45,   49,   46,   45,
      315,   45,   45,   48,   47,   44,   49,   51,   44,   47,

       50,   52,   51,   53,   68,  313,  312,   47,   45,   49,
       46,   45,  310,   45,   45,   48,   51,   47,  305,   49,
       53,   47,   50,   52,   85,   51,   85,   54,   55,   47,
       57,   49,   54,   55,   57,   57,  304,   66,   51,   57,
       54,   57,   53,   64,   57,  303,  300,   72,   64,  299,
       66,   66,   72,   67,   69,   54,   55,   91,   67,   91,
       64,   67,   54,   97,   67,   97,  153,   69,   69,   70,
      291,   64,   66,   66,   70,   72,  153,   70,   71,  290,
       70,   67,   64,  113,   67,   73,  289,   67,   74,   69,
       69,   71,   71,   73,   73,  111,   73,   70,  112,  153,

       70,   74,   74,   70,  103,  113,  103,  282,  114,  111,
      288,  287,  112,   71,   71,  282,   73,   73,  136,   73,
      136,   80,  114,   74,   74,   80,   80,  113,  110,   80,
       80,  124,   80,   87,  117,   80,  286,   87,   87,  124,
      285,   93,   87,  110,   87,   93,   93,   87,  110,   99,
       93,  117,   93,   99,   99,   93,  116,  115,   99,  119,
       99,  118,  124,   99,  115,  110,  120,  281,  121,  116,
      110,  122,  123,  117,  126,  118,  119,  128,  125,  115,
      120,  121,  276,  131,  129,  122,  123,  115,  126,  131,
      144,  116,  146,  145,  122,  149,  147,  128,  119,  131,

      148,  115,  125,  121,  129,  150,  144,  274,  146,  132,
      271,  149,  131,  132,  132,  145,  147,  122,  132,  128,
      132,  131,  148,  132,  125,  150,  129,  151,  144,  154,
      146,  152,  161,  149,  161,  183,  184,  145,  147,  168,
      185,  168,  182,  151,  148,  154,  152,  150,  182,  185,
      184,  152,  152,  269,  190,  187,  188,  183,  189,  190,
      191,  193,  192,  197,  199,  151,  191,  154,  152,  192,
      198,  182,  185,  152,  152,  187,  188,  189,  268,  183,
      208,  193,  190,  209,  198,  197,  199,  206,  235,  191,
      235,  194,  192,  208,  267,  194,  194,  187,  188,  189,

      194,  207,  194,  193,  209,  194,  198,  197,  199,  206,
      207,  210,  212,  211,  215,  208,  221,  223,  207,  213,
      214,  221,  220,  225,  210,  212,  209,  215,  224,  214,
      226,  206,  225,  207,  211,  220,  213,  223,  227,  266,
      207,  224,  241,  228,  221,  237,  210,  212,  228,  215,
      237,  229,  214,  226,  265,  225,  211,  220,  213,  223,
      227,  263,  241,  224,  229,  231,  239,  243,  238,  231,
      231,  228,  244,  237,  231,  226,  231,  238,  246,  231,
      245,  244,  227,  239,  241,  247,  229,  246,  249,  243,
      250,  251,  253,  254,  256,  249,  251,  259,  262,  261,

      238,  261,  245,  256,  244,  239,  258,  247,  255,  253,
      246,  243,  250,  254,  259,  255,  272,  270,  249,  251,
      258,  272,  273,  275,  245,  278,  256,  294,  277,  247,
      280,  253,  279,  283,  250,  254,  259,  270,  255,  273,
      275,  284,  258,  292,  272,  277,  293,  278,  294,  279,
      280,  296,  260,  301,  257,  283,  295,  298,  297,  270,
      292,  273,  275,  284,  298,  252,  293,  277,  306,  278,
      294,  279,  280,  296,  295,  297,  301,  283,  302,  307,
      314,  306,  292,  302,  308,  284,  319,  298,  293,  309,
      316,  318,  307,  320,  309,  296,  295,  297,  301,  311,

      314,  308,  319,  306,  311,  333,  302,  316,  320,  326,
      323,  318,  327,  330,  307,  323,  332,  309,  327,  329,
      248,  332,  314,  308,  319,  333,  330,  311,  242,  316,
      320,  326,  240,  318,  236,  234,  329,  233,  323,  232,
      222,  327,  219,  218,  332,  217,  216,  333,  330,  205,
      204,  203,  202,  326,  200,  196,  195,  186,  329,  336,
      336,  336,  336,  336,  336,  336,  336,  337,  337,  337,
      337,  337,  337,  337,  337,  338,  338,  338,  338,  338,
      338,  338,  338,  339,  339,  339,  339,  339,  339,  339,
      339,  340,  340,  340,  340,  340,  340,  340,  340,  341,

      181,  341,  341,  341,  341,  341,  342,  180,  342,  342,
      179,  342,  342,  343,  178,  343,  343,  177,  343,  343,
      344,  175,  344,  344,  174,  344,  344,  345,  345,  346,
      173,  346,  346,  172,  346,  346,  347,  347,  347,  171,
      347,  347,  347,  347,  348,  348,  169,  348,  348,  348,
      348,  348,  349,  349,  349,  349,  349,  349,  349,  349,
      350,  350,  350,  350,  350,  350,  350,  350,  351,  351,
      351,  351,  351,  351,  351,  351,  352,  352,  353,  353,
      353,  353,  353,  353,  353,  353,  354,  354,  354,  354,
      354,  354,  354,  354,  355,  355,  356,  356,  356,  356,

      356,  356,  356,  356,  357,  357,  357,  357,  357,  357,
      357,  357,  358,  358,  359,  359,  359,  359,  359,  359,
      359,  359,  360,  360,  360,  360,  360,  360,  360,  360,
      361,  361,  362,  362,  362,  362,  362,  362,  362,  362,
      363,  363,  363,  363,  363,  363,  363,  363,  364,  364,
      365,  167,  365,  365,  166,  365,  365,  366,  165,  366,
      366,  164,  366,  366,  367,  367,  367,  367,  367,  367,
      367,  367,  368,  368,  368,  368,  368,  368,  368,  368,
      369,  369,  370,  162,  160,  159,  158,  157,  370,  371,
      371,  372,  372,  373,  155,  142,  139,  138,  137,  373,

      374,  374,  135,  134,  133,  130,  127,  108,  107,  105,
      104,  102,  101,  100,   98,   96,   95,   94,   92,   90,
       89,   88,   86,   84,   82,   81,   79,   77,   62,   60,
       58,   42,   39,   37,   29,   28,   27,   23,    8,    7,
        6,    5,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[51] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyzer_lex.l"
/*** Definition Section ***/
#line 3 "analyzer_lex.l"
#include "analyzer.h"
bool error_lexical=false; 
unsigned int lineno=1;
char * send_error(char *error ,int line);
#line 901 "lex.yy.c"
/*%option debug*/
/*** state Section ***/

/****************************************** Rule Section ******************************************/
#line 906 "lex.yy.c"

#define INITIAL 0
#define comment 1
#define inlin_comm 2
#define string 3
#define block 4
#define if_block 5
#define if_else 6
#define for_block 7
#define while_block 8
#define matching 9
#define case_block 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "analyzer_lex.l"


#line 47 "analyzer_lex.l"
 /****************************************** Strings ******************************************/
#line 1154 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 336 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1043 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 48 "analyzer_lex.l"
{yy_push_state(string); yymore();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 49 "analyzer_lex.l"
{ yy_pop_state(); return TOK_VAR;}
	YY_BREAK
/****************************************** block_fonctions ******************************************/
case 3:
YY_RULE_SETUP
#line 53 "analyzer_lex.l"
{ return TOK_FINF ; }
	YY_BREAK
/****************************************** types ******************************************/
case 4:
YY_RULE_SETUP
#line 57 "analyzer_lex.l"
{return TOK_TYPE ; }
	YY_BREAK
/****************************************** conditions ******************************************/
case 5:
YY_RULE_SETUP
#line 61 "analyzer_lex.l"
{yy_push_state(if_block); return TOK_SI ; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "analyzer_lex.l"
{return TOK_ENTO ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "analyzer_lex.l"
{return TOK_SINON ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINB ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "analyzer_lex.l"
{yy_push_state(matching); return TOK_CAMBIAR ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "analyzer_lex.l"
{yy_push_state(case_block); return TOK_CASE ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINB ;}
	YY_BREAK
/****************************************** boucles ******************************************/
case 12:
YY_RULE_SETUP
#line 72 "analyzer_lex.l"
{yy_push_state(for_block); return TOK_POR ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "analyzer_lex.l"
{return TOK_EN ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "analyzer_lex.l"
{return TOK_DARSE ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINB ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "analyzer_lex.l"
{yy_push_state(while_block); return TOK_TANTQUE ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "analyzer_lex.l"
{return TOK_DARSE ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINB ;}
	YY_BREAK
/****************************************** E/S ******************************************/
case 19:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 83 "analyzer_lex.l"
{return TOK_LEER ;}
	YY_BREAK
case 20:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 84 "analyzer_lex.l"
{return TOK_ESCRIR ;}
	YY_BREAK
/****************************************** operateurs arithmetiques ******************************************/
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 88 "analyzer_lex.l"
{return TOK_PLUS ; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 89 "analyzer_lex.l"
{return TOK_MOINS ;}
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 90 "analyzer_lex.l"
{return TOK_MUL ;}
	YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 91 "analyzer_lex.l"
{return TOK_DIV ;}
	YY_BREAK
case 25:
/* rule 25 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 92 "analyzer_lex.l"
{return TOK_MOD ;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 93 "analyzer_lex.l"
{return TOK_PUISS ;}
	YY_BREAK
/****************************************** operateurs logiques ******************************************/
case 27:
YY_RULE_SETUP
#line 97 "analyzer_lex.l"
{return TOK_NON ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 98 "analyzer_lex.l"
{return TOK_ET ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "analyzer_lex.l"
{return TOK_OU ;}
	YY_BREAK
/****************************************** operateurs logiques ******************************************/
case 30:
YY_RULE_SETUP
#line 103 "analyzer_lex.l"
{return TOK_AFFECT ;}
	YY_BREAK
/****************************************** operateurs comparaison ******************************************/
case 31:
YY_RULE_SETUP
#line 107 "analyzer_lex.l"
{return TOK_COMP ;}
	YY_BREAK
/****************************************** operateurs decalage ******************************************/
case 32:
YY_RULE_SETUP
#line 111 "analyzer_lex.l"
{return TOK_DECAL ;}
	YY_BREAK
/****************************************** constants ******************************************/
case 33:
YY_RULE_SETUP
#line 115 "analyzer_lex.l"
{yylval.texte = yytext;	return TOK_NOMBRE;}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 117 "analyzer_lex.l"
{yylval.texte = yytext;	return TOK_STR ;}
	YY_BREAK
/****************************************** ponctuation ******************************************/	
/*{reel} {yylval.decimal=atof(yytext);	return TOK_NOMBRE;}*/
case 35:
YY_RULE_SETUP
#line 122 "analyzer_lex.l"
{return TOK_PARG ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 123 "analyzer_lex.l"
{return TOK_PARD ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 124 "analyzer_lex.l"
{return TOK_OUVR ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 125 "analyzer_lex.l"
{return TOK_FERM ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 126 "analyzer_lex.l"
{return TOK_PONC ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 127 "analyzer_lex.l"
{return TOK_FINSTR ;}
	YY_BREAK
/****************************************** identificateurs ******************************************/
case 41:
YY_RULE_SETUP
#line 131 "analyzer_lex.l"
{yylval.texte = yytext; return TOK_VAR ;}
	YY_BREAK
/****************************************** commentaires ******************************************/
case 42:
YY_RULE_SETUP
#line 135 "analyzer_lex.l"
{yy_push_state(comment); yymore();}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 136 "analyzer_lex.l"
{printf("COMMENTAIRE:\n%s\n",yytext); yy_pop_state(); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 137 "analyzer_lex.l"
{send_error(yytext,yylineno);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 138 "analyzer_lex.l"
{yy_push_state(inlin_comm); yymore();}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 139 "analyzer_lex.l"
{yy_pop_state(); }
	YY_BREAK
/****************************************** blanks ******************************************/
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 142 "analyzer_lex.l"
{lineno++;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 143 "analyzer_lex.l"
;
	YY_BREAK
/****************************************** other caracters ******************************************/
case 49:
YY_RULE_SETUP
#line 149 "analyzer_lex.l"
{send_error(yytext,yylineno);}
	YY_BREAK
/****************************************** EOF ******************************************/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(inlin_comm):
case YY_STATE_EOF(string):
case YY_STATE_EOF(block):
case YY_STATE_EOF(if_block):
case YY_STATE_EOF(if_else):
case YY_STATE_EOF(for_block):
case YY_STATE_EOF(while_block):
case YY_STATE_EOF(matching):
case YY_STATE_EOF(case_block):
#line 153 "analyzer_lex.l"
{return 0;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 155 "analyzer_lex.l"
ECHO;
	YY_BREAK
#line 1574 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 336 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 336 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 335);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 155 "analyzer_lex.l"


/****************************************** Code Section ******************************************/

char * send_error(char *error ,int line){
	//fprintf(stderr,"%s <line:%d>",error,yylineno);
	error_lexical=true ;
	return error ;
}

/*int main(){
	
 
	BEGIN(INITIAL);
	yylex();

	return 0;
}
*/

