
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[407] =
    {   0,
       57,   57,   62,   60,   61,   59,   60,   61,   58,   59,
       61,   60,   61,    1,   60,   61,   40,   60,   61,   41,
       60,   61,   60,   61,   60,   61,   48,   60,   61,   60,
       61,   60,   61,   39,   60,   61,   50,   60,   61,   51,
       60,   61,   44,   60,   61,   47,   60,   61,   52,   60,
       61,   52,   60,   61,   52,   60,   61,   52,   60,   61,
       52,   60,   61,   52,   60,   61,   52,   60,   61,   52,
       60,   61,   52,   60,   61,   52,   60,   61,   52,   60,
       61,   52,   60,   61,   52,   60,   61,   52,   60,   61,
       52,   60,   61,   43,   60,   61,   46,   60,   61,   60,

       61,   42,   60,   61,   49,   60,   61,   45,   60,   61,
       55,   61,   61,   61,   57,   61,   61,    2,   61,   52,
       60,   61,   52,   60,   61,   52,   60,   61,   52,   60,
       61,   52,   60,   61,   52,   60,   61,   52,   60,   61,
       52,   60,   61,   52,   60,   61,   52,   60,   61,   52,
       60,   61,   59,   56,   53,   24,   24,   22,   39,   22,
       23,   39,   23,   25,   25,   39,   31,   52,   52,   52,
       52,   52,16422,   52,16422,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       30,   52,   52,   52,    6,   52,   52,   27,   27,   55,

       54,   57,    2,   52,   52,   52,   52,   14,   52,   52,
       52,   52,   52,   52,   52,   24,   24,   24,   22,   22,
       22,   22,   23,   23,   23,   23,   25,   25,   25,   29,
       52,   52,   52,   52,   32,   52,   52,   52,   52,   52,
       37,   52,   35,   52,   36,   52,   34,   52,   28,   52,
       33,   13,   52,   52,   52,   52,   27,   27,   27,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   24,
       22,   23,   25,   52,   52, 8230,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   26,   52,   26,   52,   52,
       52,   52,   27,   52,    7,   52,   52,   52,   52,   52,

       52,   11,   52,   52,   52,   52,    5,   52,   52,   52,
       52,   52,   52,    5,   52,   52,   52,   26,   26,   26,
       26,   52,   26,   52,    5,   52,   52,   17,   52,   52,
       52,   15,   52,   52,   18,   52,   52,   52,   52,   52,
        5,   52,   52,   52,   52,   52,    5,   52,   52,   20,
       26,   26,   26,   52,   52,   52,   52,   52,   52,   52,
       10,   52,   52,   52,    4,    3,   20,   20,    5,   52,
       52,   52,   52,   52,   11,   52,   52,   21,   52,    5,
       52,   52,    9,   52,   52,   52,   52,   21,   21,   52,
        8,   52,   16,   52,   52,   52,    5,   52,   52,   52,

       19,   52,   52,   52,   12,   52
    } ;

static const flex_int16_t yy_accept[352] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    6,    9,   12,   14,   17,   20,
       23,   25,   27,   30,   32,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  102,  105,
      108,  111,  113,  114,  115,  117,  118,  120,  123,  126,
      129,  132,  135,  138,  141,  144,  147,  150,  153,  154,
      155,  155,  155,  155,  156,  156,  157,  158,  158,  158,
      158,  158,  160,  161,  161,  161,  161,  161,  163,  164,

      164,  164,  164,  164,  165,  166,  167,  168,  169,  170,
      171,  172,  174,  176,  177,  178,  179,  180,  181,  182,
      183,  184,  185,  186,  187,  188,  189,  190,  191,  193,
      194,  195,  197,  198,  198,  198,  198,  198,  199,  200,
      201,  201,  202,  203,  203,  204,  205,  206,  207,  208,
      210,  211,  212,  213,  214,  215,  216,  216,  217,  217,
      217,  218,  219,  220,  220,  221,  221,  221,  222,  223,
      224,  224,  225,  225,  225,  226,  227,  227,  228,  228,
      228,  229,  230,  232,  233,  234,  234,  235,  236,  237,
      238,  239,  240,  241,  242,  243,  244,  245,  246,  247,

      248,  249,  251,  252,  254,  255,  256,  257,  257,  258,
      258,  258,  259,  260,  261,  262,  263,  264,  265,  266,
      267,  268,  269,  270,  271,  272,  273,  274,  275,  276,
      277,  278,  279,  280,  281,  282,  283,  284,  285,  286,
      286,  286,  286,  286,  288,  290,  291,  292,  293,  294,
      295,  297,  298,  299,  300,  301,  302,  304,  305,  306,
      307,  309,  310,  311,  312,  313,  314,  316,  317,  318,
      318,  318,  319,  320,  320,  321,  321,  321,  323,  325,
      327,  328,  330,  331,  332,  334,  335,  337,  338,  339,
      340,  341,  343,  344,  345,  346,  347,  349,  350,  350,

      351,  352,  353,  354,  355,  356,  357,  358,  359,  360,
      361,  363,  363,  363,  364,  365,  366,  367,  368,  369,
      371,  372,  373,  374,  375,  377,  378,  378,  379,  380,
      382,  383,  385,  386,  387,  388,  389,  390,  391,  393,
      395,  396,  397,  399,  400,  401,  403,  404,  405,  407,
      407
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
        1,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   28,   28,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   28,   28,   28,   40,   28,
       41,    1,   42,   43,    1,    1,   44,   45,   46,   47,

       48,   49,   50,   28,   51,   28,   28,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   28,   28,   28,
       62,   28,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    3,    1,    1,    4,    5,    1,    1,    6,
        5,    1,    5,    1,    1,    7,    1,    1,    1,    1,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[388] =
    {   0,
        0,    0,   60,   61, 1069, 1068, 1064, 1063,    0,    0,
       49,   53,   42,   43,   56,   59,   62,   63,   70,   97,
       51,   64, 1068, 1073,  122,  125, 1062, 1073, 1073, 1073,
      129,  145, 1073,  153,  161, 1050, 1073, 1073, 1052, 1073,
      116, 1048,  141,  149,  155,  159,  170,  162,  181,  165,
      205,  166,  168,  215,  211, 1073, 1073,  232, 1073, 1073,
     1073, 1053, 1073, 1052,    0, 1055, 1073,  221,   83,  217,
      236,  151,  242,  240,  259,  257,  275,  266,  301, 1073,
      322, 1054, 1052, 1073, 1042,  237, 1041,  334, 1050, 1048,
     1038,  263, 1037,  342, 1046, 1041, 1031,  292, 1030,  350,

     1039, 1037, 1021,  293, 1020, 1019, 1073, 1018, 1017,  106,
      315,  201,  296,  175,  311,  344,  314,  265,  304,  360,
      338,  362,  354,  370,  372,  353,  188,  373,  995,  363,
      365,  992,  375,  406,  998,  994,  880,  300,  873,  873,
      870, 1073,    0,  868, 1073,  371,  364,  378,  380,  368,
      382,  395,  410,  414,  411,  417,  865, 1073,  860,  848,
      844,  841,  425,  844, 1073,  816,  806,  805,  804,  430,
      813, 1073,  811,  801,  800,  799,  808, 1073,  806,  796,
      795,  794,  793,  418,  419,  445,  427,  806,  432,  438,
      442,  440,  449,  805,  460,  804,  269,  803,  450,  801,

      481,  785,  798,  781,  443,  468,  462,  790, 1073,  788,
      776,  775,  772,  464,  479,  485,  469,  494,  493,  497,
      499,  491,  502,  771,  770,  767,  762,  509,  519,  732,
      501,  513,  525,  505,  473,  527,  530,  533,  553,  565,
      713,  709,  696,  542,  694,  554,  552,  563,  693,  566,
      668,  567,  564,  569,  572,  570,  665,  369,  575,  578,
      664,  576,  574,  588,  590,  600,  662,  587,  603,  593,
      666,  607,  650,  656, 1073,  652,  637,  612,  598,  577,
      609,  541,  621,  624,  531,  627,  503,  628,  610,  630,
      633,  446,  648,  635,  636,  673,  439,  684,  407,  326,

      323,  318,  310,  638,  656,  695,  699,  702,  674,  718,
      305,  639,  272,  678,  692,  721,  724,  254,  209,  191,
      714,  715,  719,  726,  164,  729,  177,  138,  721,  134,
      730,  133,  722,  735,  737,  125,  122,  740,  118,  117,
      733,  753,  102,  744,  743,   98,  760,  766,   57, 1073,
      824,  832,  840,  847,  854,  861,  868,  870,  877,  885,
      893,  901,  909,  917,  919,  927,  935,  937,  945,  953,
      955,  963,  971,  973,  981,  989,  991,  998, 1005, 1013,
     1021, 1023, 1030, 1032, 1034, 1041, 1043
    } ;

static const flex_int16_t yy_def[388] =
    {   0,
      350,    1,  351,  351,  352,  352,  353,  353,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  350,  350,  350,  350,  350,  350,  350,  350,
      354,  355,  350,  356,  357,  350,  350,  350,  350,  350,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  350,  350,  359,  350,  350,
      350,  360,  350,  350,  361,  362,  350,  358,   45,  358,
      358,   45,  358,  358,  358,  358,  358,  358,  350,  350,
      354,  363,  364,  350,  350,  350,  365,  355,  366,  367,
      350,  350,  368,  356,  369,  370,  350,  350,  371,  357,

      372,  373,  350,  350,  374,  350,  350,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  359,  375,  376,  350,  350,  377,  360,
      350,  350,  361,  362,  350,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  363,  350,  364,  350,
      365,  365,  350,  366,  350,  367,  350,  368,  368,  350,
      369,  350,  370,  350,  371,  371,  372,  350,  373,  350,
      374,  374,  358,  358,  358,  350,  358,  350,  358,  358,
      358,  358,  358,  350,  358,  350,  358,  350,  358,  350,

      378,  358,  350,  358,  358,  358,  358,  375,  350,  376,
      350,  377,  377,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  350,  350,  350,  350,  358,  358,  350,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  379,
      380,  381,  350,  358,  382,  358,  358,  358,  350,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  350,
      383,  350,  384,  380,  350,  381,  350,  382,  382,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  383,  385,

      384,  384,  350,  358,  358,  358,  358,  358,  358,  358,
      358,  350,  386,  358,  358,  350,  350,  385,  385,  358,
      358,  358,  358,  358,  358,  358,  386,  387,  358,  358,
      358,  358,  358,  358,  358,  387,  387,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350
    } ;

static const flex_int16_t yy_nxt[1139] =
    {   0,
       24,   25,   26,   25,   27,   28,   24,   29,   30,   31,
       32,   33,   34,   24,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   42,   48,   49,
       50,   51,   52,   53,   42,   42,   54,   55,   42,   42,
       56,   57,   58,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   42,   42,   54,   55,
       42,   42,   59,   60,   61,   63,   63,   70,   70,   64,
       64,   68,  108,   69,   70,   68,   78,   69,   70,   71,
       72,   73,   71,   72,   73,   74,   74,   75,   75,   78,
       70,   70,   76,   77,   68,   78,   69,   70,   68,   78,

       69,   70,   71,   72,   73,   71,   72,   73,   74,   74,
       75,   75,   78,  108,  147,   76,   77,  108,   78,   76,
       77,  108,   78,   79,   79,   79,   79,   79,   79,  183,
       81,  108,  108,  108,   82,   83,  147,  336,   84,   85,
      336,   85,   76,   77,   86,   78,   88,  110,  108,  108,
       89,   90,  183,  336,   94,   91,  108,   91,   95,   96,
       92,  111,  100,   97,  108,   97,  101,  102,   98,  110,
      108,  103,  112,  103,  108,  113,  104,  108,  327,  108,
      108,  108,  150,  108,  111,  108,  114,  118,  119,  115,
      108,  116,  117,  123,  120,  112,  108,  126,  113,  121,

      130,  129,  186,  108,  150,  124,  108,  122,  114,  118,
      119,  115,  187,  116,  117,  123,  108,  120,  125,  126,
      108,  121,  130,  129,  318,  127,  108,  202,  124,  122,
      108,  133,  108,  134,  187,  131,  108,  135,  136,  128,
      125,  111,  137,  132,  137,  148,  119,  138,  127,  202,
      160,  108,   86,  146,  133,  108,  149,  108,  131,  112,
      152,  128,  113,  112,  111,  132,  113,  148,  119,  318,
      151,  119,  108,  327,  108,  146,  167,  154,   92,  149,
      108,  108,  112,  152,  108,  113,  112,  153,  119,  113,
      108,  238,  151,  119,  156,  119,  192,  186,  112,  155,

      154,  113,   79,   79,   79,  174,  180,   98,  104,  153,
      119,  108,  188,  211,  238,  138,  156,  119,  192,  108,
      108,  112,  155,   81,  113,  303,  108,   82,   83,  108,
      108,  350,   85,  301,   85,   88,  193,   86,  301,   89,
       90,  318,  191,   94,   91,  184,   91,   95,   96,  163,
      185,  100,   97,  108,   97,  101,  102,  170,  193,  108,
      103,  194,  103,  196,  191,  104,  189,  184,  108,  108,
      195,  198,  185,  200,  203,  108,  201,  108,  108,  108,
      108,  190,  197,  108,  108,  108,  108,  108,  108,  189,
      108,  289,  195,  108,  199,  108,  206,  108,  204,  201,

      205,  215,  214,  190,  197,  187,  207,  134,  299,  216,
      108,  135,  136,  218,  289,  217,  137,  199,  137,  206,
      204,  138,  205,  215,  214,  108,  108,  187,  207,  108,
      219,  216,  108,  108,  108,  218,  222,  217,  167,  228,
      163,  220,  108,  174,  184,  170,  186,  108,  223,  185,
      221,  231,  219,  108,  108,  108,  229,  108,  108,  222,
      230,  108,  228,  220,  108,  108,  184,  232,  235,  236,
      223,  185,  221,  233,  231,  108,  234,  108,  229,  108,
      246,  237,  240,  108,  108,  239,  241,  242,  108,  232,
      235,  243,  236,  243,  108,  233,  244,  247,  234,  248,

      108,  250,  246,  231,  237,  253,  108,  239,  108,  108,
      266,  251,  108,  252,  108,  258,  108,  108,  108,  247,
      108,  248,  254,  250,  108,  256,  231,  253,  108,  255,
      259,  257,  266,  251,  108,  252,  262,  260,  258,  261,
      108,  263,  108,  265,  254,  108,  108,  256,  108,  264,
      268,  255,  259,  257,  270,  277,  108,  244,  262,  260,
      271,  269,  261,  263,  267,  265,  240,  108,  108,  108,
      241,  242,  264,  268,  280,  243,  281,  243,  108,  108,
      272,  108,  108,  269,  108,  108,  267,  108,  285,  108,
      108,  108,  108,  108,  270,  282,  287,  280,  291,  281,

      271,  283,  108,  108,  284,  108,  286,  288,  292,  293,
      294,  285,  290,  278,  295,  108,  297,  282,  108,  287,
      277,  291,  272,  283,  108,  108,  284,  278,  286,  288,
      292,  293,  296,  294,  290,  298,  108,  295,  297,  108,
      312,  305,  108,  108,  304,  108,  313,  309,  108,  312,
      108,  108,  303,  108,  296,  313,  306,  298,  275,  307,
      308,  275,  310,  108,  305,  301,  304,  299,  311,  309,
      320,  108,  314,  315,  316,  316,  316,  108,  306,  108,
      108,  307,  308,  108,  310,  317,  317,  317,  108,  108,
      311,  321,  320,  108,  314,  315,  316,  316,  316,  108,

      316,  316,  316,  316,  316,  316,  325,  108,  249,  278,
      108,  272,  330,  321,  108,  275,  329,  108,  275,  316,
      316,  316,  316,  316,  316,  317,  317,  317,  325,  108,
      108,  322,  323,  108,  108,  330,  108,  108,  329,  324,
      326,  108,  331,  332,  108,  108,  334,  230,  108,  335,
      108,  333,  108,  322,  323,  108,  338,  340,  108,  108,
      343,  324,  339,  326,  331,  332,  341,  342,  108,  334,
      344,  347,  335,  333,  345,  108,  346,  227,  338,  340,
      348,  108,  226,  343,  339,  225,  224,  212,  341,  342,
      212,  249,  344,  347,  209,  209,  108,  345,  346,  203,

      108,  349,  200,  348,  198,  196,  194,  188,  108,  181,
      181,  227,  178,  178,  175,  175,  226,  172,  172,  168,
      168,  225,  165,  349,   62,   62,   62,   62,   62,   62,
       62,   62,   65,   65,   65,   65,   65,   65,   65,   65,
       66,   66,   66,   66,   66,   66,   66,   66,   87,  165,
       87,   87,   87,   87,   87,   93,  161,   93,   93,  161,
       93,   93,   99,  224,   99,   99,  158,   99,   99,  105,
      158,  105,  105,  145,  105,  105,  109,  109,  139,  142,
      139,  139,  141,  139,  139,  140,  140,  140,  212,  140,
      140,  140,  140,  143,  143,  138,  143,  143,  143,  143,

      143,  144,  144,  144,  144,  144,  144,  144,  144,  157,
      157,  157,  157,  157,  157,  157,  157,  159,  159,  159,
      159,  159,  159,  159,  159,  162,  162,  164,  164,  164,
      164,  164,  164,  164,  164,  166,  166,  166,  166,  166,
      166,  166,  166,  169,  169,  171,  171,  171,  171,  171,
      171,  171,  171,  173,  173,  173,  173,  173,  173,  173,
      173,  176,  176,  177,  177,  177,  177,  177,  177,  177,
      177,  179,  179,  179,  179,  179,  179,  179,  179,  182,
      182,  208,  208,  208,  208,  208,  208,  208,  208,  210,
      210,  210,  210,  210,  210,  210,  210,  213,  213,  245,

      209,  245,  245,  209,  245,  245,  273,  108,  273,  273,
      108,  273,  273,  274,  274,  274,  274,  274,  274,  274,
      274,  276,  276,  276,  276,  276,  276,  276,  276,  279,
      279,  300,  108,  108,  106,  181,  104,  300,  302,  302,
      319,  319,  328,  178,  178,  175,  170,  172,  328,  337,
      337,  172,  168,  163,  165,  165,  161,   86,  158,  158,
      145,  142,  141,  108,  107,  106,   80,  350,   67,   67,
       63,   63,   23,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350
    } ;

static const flex_int16_t yy_chk[1139] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,   13,   14,    3,
        4,   11,  349,   11,   11,   12,   21,   12,   12,   15,
       15,   15,   16,   16,   16,   17,   18,   17,   18,   22,
       13,   14,   19,   19,   11,   19,   11,   11,   12,   21,

       12,   12,   15,   15,   15,   16,   16,   16,   17,   18,
       17,   18,   22,  346,   69,   19,   19,  343,   19,   20,
       20,  110,   20,   25,   25,   25,   26,   26,   26,  110,
       31,   41,  340,  339,   31,   31,   69,  337,   31,   31,
      336,   31,   20,   20,   31,   20,   32,   41,  332,  330,
       32,   32,  110,  328,   34,   32,   43,   32,   34,   34,
       32,   43,   35,   34,   44,   34,   35,   35,   34,   41,
       45,   35,   44,   35,   46,   44,   35,   48,  327,  325,
       50,   52,   72,   53,   43,   47,   45,   46,   46,   45,
      114,   45,   45,   48,   47,   44,   49,   50,   44,   47,

       53,   52,  112,  127,   72,   49,  320,   47,   45,   46,
       46,   45,  114,   45,   45,   48,  112,   47,   49,   50,
       51,   47,   53,   52,  319,   51,   55,  127,   49,   47,
       54,   55,   70,   58,  114,   54,   68,   58,   58,   51,
       49,   68,   58,   54,   58,   70,   70,   58,   51,  127,
       86,   71,   86,   68,   55,   74,   71,   73,   54,   71,
       74,   51,   71,   74,   68,   54,   74,   70,   70,  318,
       73,   73,   76,  313,   75,   68,   92,   76,   92,   71,
      118,   78,   71,   74,  197,   71,   74,   75,   75,   74,
       77,  197,   73,   73,   78,   78,  118,  113,   77,   77,

       76,   77,   79,   79,   79,   98,  104,   98,  104,   75,
       75,  113,  115,  138,  197,  138,   78,   78,  118,  119,
      311,   77,   77,   81,   77,  303,  115,   81,   81,  117,
      111,   81,   81,  302,   81,   88,  119,   81,  301,   88,
       88,  300,  117,   94,   88,  111,   88,   94,   94,   88,
      111,  100,   94,  121,   94,  100,  100,   94,  119,  116,
      100,  120,  100,  122,  117,  100,  116,  111,  126,  123,
      121,  124,  111,  125,  128,  120,  126,  122,  130,  147,
      131,  116,  123,  150,  258,  124,  146,  125,  128,  116,
      133,  258,  121,  148,  124,  149,  133,  151,  130,  126,

      131,  147,  146,  116,  123,  150,  133,  134,  299,  148,
      152,  134,  134,  151,  258,  149,  134,  124,  134,  133,
      130,  134,  131,  147,  146,  153,  155,  150,  133,  154,
      152,  148,  156,  184,  185,  151,  155,  149,  163,  184,
      163,  153,  187,  170,  154,  170,  186,  189,  156,  154,
      154,  187,  152,  190,  297,  192,  185,  191,  205,  155,
      186,  292,  184,  153,  193,  199,  154,  189,  192,  193,
      156,  154,  154,  190,  187,  195,  191,  207,  185,  214,
      205,  195,  201,  206,  217,  199,  201,  201,  235,  189,
      192,  201,  193,  201,  215,  190,  201,  206,  191,  207,

      216,  214,  205,  215,  195,  217,  222,  199,  219,  218,
      235,  215,  220,  216,  221,  222,  231,  223,  287,  206,
      234,  207,  218,  214,  228,  220,  215,  217,  232,  219,
      223,  221,  235,  215,  229,  216,  231,  228,  222,  229,
      233,  232,  236,  234,  218,  237,  285,  220,  238,  233,
      237,  219,  223,  221,  239,  244,  282,  244,  231,  228,
      239,  238,  229,  232,  236,  234,  240,  247,  239,  246,
      240,  240,  233,  237,  246,  240,  247,  240,  248,  253,
      240,  250,  252,  238,  254,  256,  236,  255,  253,  263,
      259,  262,  280,  260,  270,  248,  255,  246,  260,  247,

      270,  250,  268,  264,  252,  265,  254,  256,  262,  263,
      264,  253,  259,  279,  265,  266,  268,  248,  269,  255,
      272,  260,  272,  250,  281,  289,  252,  278,  254,  256,
      262,  263,  266,  264,  259,  269,  283,  265,  268,  284,
      312,  283,  286,  288,  281,  290,  312,  289,  291,  293,
      294,  295,  277,  304,  266,  293,  284,  269,  276,  286,
      288,  274,  290,  293,  283,  273,  281,  271,  291,  289,
      304,  305,  294,  295,  296,  296,  296,  267,  284,  261,
      257,  286,  288,  251,  290,  298,  298,  298,  296,  309,
      291,  305,  304,  314,  294,  295,  306,  306,  306,  298,

      307,  307,  307,  308,  308,  308,  309,  315,  249,  245,
      306,  243,  315,  305,  307,  242,  314,  308,  241,  310,
      310,  310,  316,  316,  316,  317,  317,  317,  309,  321,
      322,  306,  307,  310,  323,  315,  329,  333,  314,  308,
      310,  324,  321,  322,  326,  331,  324,  230,  341,  326,
      334,  323,  335,  306,  307,  338,  329,  333,  345,  344,
      338,  308,  331,  310,  321,  322,  334,  335,  342,  324,
      341,  345,  326,  323,  342,  347,  344,  227,  329,  333,
      347,  348,  226,  338,  331,  225,  224,  213,  334,  335,
      212,  211,  341,  345,  210,  208,  204,  342,  344,  203,

      202,  348,  200,  347,  198,  196,  194,  188,  183,  182,
      181,  180,  179,  177,  176,  175,  174,  173,  171,  169,
      168,  167,  166,  348,  351,  351,  351,  351,  351,  351,
      351,  351,  352,  352,  352,  352,  352,  352,  352,  352,
      353,  353,  353,  353,  353,  353,  353,  353,  354,  164,
      354,  354,  354,  354,  354,  355,  162,  355,  355,  161,
      355,  355,  356,  160,  356,  356,  159,  356,  356,  357,
      157,  357,  357,  144,  357,  357,  358,  358,  359,  141,
      359,  359,  140,  359,  359,  360,  360,  360,  139,  360,
      360,  360,  360,  361,  361,  137,  361,  361,  361,  361,

      361,  362,  362,  362,  362,  362,  362,  362,  362,  363,
      363,  363,  363,  363,  363,  363,  363,  364,  364,  364,
      364,  364,  364,  364,  364,  365,  365,  366,  366,  366,
      366,  366,  366,  366,  366,  367,  367,  367,  367,  367,
      367,  367,  367,  368,  368,  369,  369,  369,  369,  369,
      369,  369,  369,  370,  370,  370,  370,  370,  370,  370,
      370,  371,  371,  372,  372,  372,  372,  372,  372,  372,
      372,  373,  373,  373,  373,  373,  373,  373,  373,  374,
      374,  375,  375,  375,  375,  375,  375,  375,  375,  376,
      376,  376,  376,  376,  376,  376,  376,  377,  377,  378,

      136,  378,  378,  135,  378,  378,  379,  132,  379,  379,
      129,  379,  379,  380,  380,  380,  380,  380,  380,  380,
      380,  381,  381,  381,  381,  381,  381,  381,  381,  382,
      382,  383,  109,  108,  106,  105,  103,  383,  384,  384,
      385,  385,  386,  102,  101,   99,   97,   96,  386,  387,
      387,   95,   93,   91,   90,   89,   87,   85,   83,   82,
       66,   64,   62,   42,   39,   36,   27,   23,    8,    7,
        6,    5,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[62] =
    {   0,
0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 
    0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyzer_lex.l"
/*** Definition Section ***/
#line 3 "analyzer_lex.l"
#include "analyzer.h"
bool error_lexical=false; 
unsigned int lineno=1;
char * send_error(char *error ,int line);
#line 915 "lex.yy.c"
/*%option debug*/
/*** state Section ***/

/****************************************** Rule Section ******************************************/
#line 920 "lex.yy.c"

#define INITIAL 0
#define comment 1
#define inlin_comm 2
#define string 3
#define block 4
#define if_block 5
#define if_else 6
#define for_block 7
#define while_block 8
#define matching 9
#define case_block 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "analyzer_lex.l"


#line 47 "analyzer_lex.l"
 /****************************************** Strings ******************************************/
#line 1168 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1073 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 48 "analyzer_lex.l"
{yy_push_state(string); yymore();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 49 "analyzer_lex.l"
{ yy_pop_state(); yylval.texte = yytext; return TOK_STR;}
	YY_BREAK
/****************************************** block_fonctions ******************************************/
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 53 "analyzer_lex.l"
{ return TOK_FINI ; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 54 "analyzer_lex.l"
{ return TOK_FINF ; }
	YY_BREAK
/****************************************** types ******************************************/
case 5:
YY_RULE_SETUP
#line 58 "analyzer_lex.l"
{return TOK_TYPE ; }
	YY_BREAK
/****************************************** conditions ******************************************/
case 6:
YY_RULE_SETUP
#line 62 "analyzer_lex.l"
{yy_push_state(if_block); return TOK_SI ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "analyzer_lex.l"
{return TOK_ALORS ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "analyzer_lex.l"
{return TOK_SINON ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINSI ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "analyzer_lex.l"
{yy_push_state(matching); return TOK_CAMBIAR ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "analyzer_lex.l"
{yy_push_state(case_block); return TOK_CASE ;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINB ;}
	YY_BREAK
/****************************************** boucles ******************************************/
case 13:
YY_RULE_SETUP
#line 73 "analyzer_lex.l"
{yy_push_state(for_block); return TOK_FOR ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "analyzer_lex.l"
{return TOK_DANS ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "analyzer_lex.l"
{return TOK_FAIRE ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINFOR ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "analyzer_lex.l"
{yy_push_state(while_block); return TOK_TANT ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "analyzer_lex.l"
{return TOK_FAIRE ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 80 "analyzer_lex.l"
{yy_pop_state(); return TOK_FINT ;}
	YY_BREAK
/****************************************** E/S ******************************************/
case 20:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 84 "analyzer_lex.l"
{return TOK_LEER ;}
	YY_BREAK
case 21:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 85 "analyzer_lex.l"
{return TOK_ESCRIR ;}
	YY_BREAK
/****************************************** operateurs arithmetiques ******************************************/
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 89 "analyzer_lex.l"
{return TOK_PLUS ; }
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 90 "analyzer_lex.l"
{return TOK_MOINS ;}
	YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 91 "analyzer_lex.l"
{return TOK_MUL ;}
	YY_BREAK
case 25:
/* rule 25 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 92 "analyzer_lex.l"
{return TOK_DIV ;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 93 "analyzer_lex.l"
{return TOK_MOD ;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 94 "analyzer_lex.l"
{return TOK_PUISS ;}
	YY_BREAK
/****************************************** operateurs logiques ******************************************/
case 28:
YY_RULE_SETUP
#line 98 "analyzer_lex.l"
{return TOK_NON ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "analyzer_lex.l"
{return TOK_ET ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "analyzer_lex.l"
{return TOK_OU ;}
	YY_BREAK
/****************************************** operateurs logiques ******************************************/
case 31:
YY_RULE_SETUP
#line 104 "analyzer_lex.l"
{return TOK_AFFECT ;}
	YY_BREAK
/****************************************** operateurs comparaison ******************************************/
case 32:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 108 "analyzer_lex.l"
{return TOK_EQ ;}
	YY_BREAK
case 33:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 109 "analyzer_lex.l"
{return TOK_NQ ;}
	YY_BREAK
case 34:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 110 "analyzer_lex.l"
{return TOK_LT ;}
	YY_BREAK
case 35:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 111 "analyzer_lex.l"
{return TOK_GT ;}
	YY_BREAK
case 36:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 112 "analyzer_lex.l"
{return TOK_LE ;}
	YY_BREAK
case 37:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 113 "analyzer_lex.l"
{return TOK_GE ;}
	YY_BREAK
/****************************************** operateurs decalage ******************************************/
case 38:
YY_RULE_SETUP
#line 117 "analyzer_lex.l"
{return TOK_DECAL ;}
	YY_BREAK
/****************************************** constants ******************************************/
case 39:
YY_RULE_SETUP
#line 121 "analyzer_lex.l"
{yylval.texte = yytext;	return TOK_NOMBRE;}
	YY_BREAK
/****************************************** ponctuation ******************************************/	
/*{reel} {yylval.decimal=atof(yytext);	return TOK_NOMBRE;}*/
case 40:
YY_RULE_SETUP
#line 126 "analyzer_lex.l"
{return TOK_PARG ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "analyzer_lex.l"
{return TOK_PARD ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 129 "analyzer_lex.l"
{return TOK_ACCOLG ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "analyzer_lex.l"
{return TOK_BRACKG ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "analyzer_lex.l"
{return TOK_OUVR ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 133 "analyzer_lex.l"
{return TOK_ACCOLD ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 134 "analyzer_lex.l"
{return TOK_BRACKD ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 135 "analyzer_lex.l"
{return TOK_FERM ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 137 "analyzer_lex.l"
{return TOK_VIRG ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "analyzer_lex.l"
{return TOK_PIPE ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 139 "analyzer_lex.l"
{return TOK_DPTS ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 141 "analyzer_lex.l"
{return TOK_FINSTR ;}
	YY_BREAK
/****************************************** identificateurs ******************************************/
case 52:
YY_RULE_SETUP
#line 145 "analyzer_lex.l"
{yylval.texte = yytext; return TOK_VAR ;}
	YY_BREAK
/****************************************** commentaires ******************************************/
case 53:
YY_RULE_SETUP
#line 149 "analyzer_lex.l"
{yy_push_state(comment);}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 150 "analyzer_lex.l"
{yy_pop_state(); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 151 "analyzer_lex.l"
{send_error(yytext,yylineno);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 152 "analyzer_lex.l"
{yy_push_state(inlin_comm);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 153 "analyzer_lex.l"
{yy_pop_state(); }
	YY_BREAK
/****************************************** blanks ******************************************/
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 156 "analyzer_lex.l"
{lineno++;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 157 "analyzer_lex.l"
;
	YY_BREAK
/****************************************** other caracters ******************************************/
case 60:
YY_RULE_SETUP
#line 163 "analyzer_lex.l"
{send_error(yytext,yylineno);}
	YY_BREAK
/****************************************** EOF ******************************************/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(inlin_comm):
case YY_STATE_EOF(string):
case YY_STATE_EOF(block):
case YY_STATE_EOF(if_block):
case YY_STATE_EOF(if_else):
case YY_STATE_EOF(for_block):
case YY_STATE_EOF(while_block):
case YY_STATE_EOF(matching):
case YY_STATE_EOF(case_block):
#line 167 "analyzer_lex.l"
{return 0;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 169 "analyzer_lex.l"
ECHO;
	YY_BREAK
#line 1670 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 350);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 169 "analyzer_lex.l"


/****************************************** Code Section ******************************************/

char * send_error(char *error ,int line){
	error_lexical=true ;
	return error ;
}


